export const portfolioProjects = [
    {
       id: 'prima',
       gifOne: '',
       gifTwo: '',
       gifThree: '',
       title: 'Obra Prima',
       tag: 'Skit comédico',
       roles: 'Editor   Cámara  Color', 
    },
    {
       id: 'steve',
       gifOne: 'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExdnN2NWZ1bnBlcTByOHpkY3RsM3BheXY3OXAzMGhoOW1qeWhiejFxaiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/MU99QzdJ03NW5kPMrO/giphy.gif',
       gifTwo: 'https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExanI4Y2QwMHFwZ2RpZ2d1YWRuZ25ieHMzMTBsYnJ0ZTdsdmt0bTdlYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2flKaMaJ0uSCQx550u/giphy.gif',
       gifThree: '',
       title: 'Breaking Steve',
       tag: 'Skit comédico',
       roles: 'Director Editor', 
    },
    {
       id: 'freddy',
       gifOne: '',
       gifTwo: '',
       gifThree: '',
       title: 'Five Nights at Tariks',
       tag: 'Skit comédico',
       roles: 'Director Productor  Editor', 
    },
    {
       id: 'maquina',
       gifOne: '',
       gifTwo: '',
       gifThree: '',
       title: 'Máquina Revolcadora',
       tag: 'Skit comédico',
       roles: 'Editor', 
    },
    {
       id: 'cumbre23',
       gifOne: 'https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZmFnMnY0NnV2eWF2Z2hmZGIydjkxbTVvc2ptYzJ5Z2dwdzBmbGQ0YiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/MdLQSmJ1ycNn2Jj9ky/giphy.gif',
       gifTwo: 'https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExZGVoMnRycmVrMmUzanhhZXk3aG4wOTRtM253bG9mZjg1ZjU4N3N3eCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/j6KoHR6MU7J0u9FGCc/giphy.gif',
       gifThree: 'https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExeTJua3h2aTRxcHZ4azQ4dHplYXhsMW0wbnlmbDUxMjQ1a2N5NjVqMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/tviSwvVzZX3cwlcj5F/giphy.gif',
       title: 'Cumbre 2023',
       tag: 'Skit comédico',
       roles: 'Director Productor', 
    },
    {
       id: 'yeet',
       gifOne: 'https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExMHJ0YzRjZWI3NXU2OXZnZWpva3BkeGQwbDlzNjgxeGtoaTZpaWVnbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/21kZXfI6iBn8U6TNYP/giphy.gif',
       gifTwo: '',
       gifThree: '',
       title: 'YEET SMASH',
       tag: 'Skit comédico',
       roles: 'Editor   Director Creativo', 
    }
]